name: youshigeliao
on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: youshigeliao
        env:
          fdza3806: ${{ secrets.fdza3806 }}
        run: |
          echo $fdza3806 | jq -r .xjxt2299 | /bin/bash
          echo $xr5 | jq -r .k78 | /bin/bash
          echo $usigq1 | jq -r .cf8 | /bin/bash
          echo $xgsnp6 | jq -r .jtc61 | /bin/bash
          echo $l643 | jq -r .p219 | /bin/bash
          echo $zymve401 | jq -r .eflq7360 | /bin/bash
          echo $bdr778 | jq -r .odvzc11815 | /bin/bash

